# CMake generated Testfile for 
# Source directory: C:/Users/daris/Documents/Saclay/ReseauDeNeurones/nn/tests
# Build directory: C:/Users/daris/Documents/Saclay/ReseauDeNeurones/nn/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_activation "C:/Users/daris/Documents/Saclay/ReseauDeNeurones/nn/tests/Debug/test_activation.exe")
  set_tests_properties(test_activation PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/daris/Documents/Saclay/ReseauDeNeurones/nn/tests/CMakeLists.txt;14;add_test;C:/Users/daris/Documents/Saclay/ReseauDeNeurones/nn/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_activation "C:/Users/daris/Documents/Saclay/ReseauDeNeurones/nn/tests/Release/test_activation.exe")
  set_tests_properties(test_activation PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/daris/Documents/Saclay/ReseauDeNeurones/nn/tests/CMakeLists.txt;14;add_test;C:/Users/daris/Documents/Saclay/ReseauDeNeurones/nn/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_activation "C:/Users/daris/Documents/Saclay/ReseauDeNeurones/nn/tests/MinSizeRel/test_activation.exe")
  set_tests_properties(test_activation PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/daris/Documents/Saclay/ReseauDeNeurones/nn/tests/CMakeLists.txt;14;add_test;C:/Users/daris/Documents/Saclay/ReseauDeNeurones/nn/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_activation "C:/Users/daris/Documents/Saclay/ReseauDeNeurones/nn/tests/RelWithDebInfo/test_activation.exe")
  set_tests_properties(test_activation PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/daris/Documents/Saclay/ReseauDeNeurones/nn/tests/CMakeLists.txt;14;add_test;C:/Users/daris/Documents/Saclay/ReseauDeNeurones/nn/tests/CMakeLists.txt;0;")
else()
  add_test(test_activation NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_matrix "C:/Users/daris/Documents/Saclay/ReseauDeNeurones/nn/tests/Debug/test_matrix.exe")
  set_tests_properties(test_matrix PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/daris/Documents/Saclay/ReseauDeNeurones/nn/tests/CMakeLists.txt;14;add_test;C:/Users/daris/Documents/Saclay/ReseauDeNeurones/nn/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_matrix "C:/Users/daris/Documents/Saclay/ReseauDeNeurones/nn/tests/Release/test_matrix.exe")
  set_tests_properties(test_matrix PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/daris/Documents/Saclay/ReseauDeNeurones/nn/tests/CMakeLists.txt;14;add_test;C:/Users/daris/Documents/Saclay/ReseauDeNeurones/nn/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_matrix "C:/Users/daris/Documents/Saclay/ReseauDeNeurones/nn/tests/MinSizeRel/test_matrix.exe")
  set_tests_properties(test_matrix PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/daris/Documents/Saclay/ReseauDeNeurones/nn/tests/CMakeLists.txt;14;add_test;C:/Users/daris/Documents/Saclay/ReseauDeNeurones/nn/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_matrix "C:/Users/daris/Documents/Saclay/ReseauDeNeurones/nn/tests/RelWithDebInfo/test_matrix.exe")
  set_tests_properties(test_matrix PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/daris/Documents/Saclay/ReseauDeNeurones/nn/tests/CMakeLists.txt;14;add_test;C:/Users/daris/Documents/Saclay/ReseauDeNeurones/nn/tests/CMakeLists.txt;0;")
else()
  add_test(test_matrix NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_network "C:/Users/daris/Documents/Saclay/ReseauDeNeurones/nn/tests/Debug/test_network.exe")
  set_tests_properties(test_network PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/daris/Documents/Saclay/ReseauDeNeurones/nn/tests/CMakeLists.txt;14;add_test;C:/Users/daris/Documents/Saclay/ReseauDeNeurones/nn/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_network "C:/Users/daris/Documents/Saclay/ReseauDeNeurones/nn/tests/Release/test_network.exe")
  set_tests_properties(test_network PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/daris/Documents/Saclay/ReseauDeNeurones/nn/tests/CMakeLists.txt;14;add_test;C:/Users/daris/Documents/Saclay/ReseauDeNeurones/nn/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_network "C:/Users/daris/Documents/Saclay/ReseauDeNeurones/nn/tests/MinSizeRel/test_network.exe")
  set_tests_properties(test_network PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/daris/Documents/Saclay/ReseauDeNeurones/nn/tests/CMakeLists.txt;14;add_test;C:/Users/daris/Documents/Saclay/ReseauDeNeurones/nn/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_network "C:/Users/daris/Documents/Saclay/ReseauDeNeurones/nn/tests/RelWithDebInfo/test_network.exe")
  set_tests_properties(test_network PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/daris/Documents/Saclay/ReseauDeNeurones/nn/tests/CMakeLists.txt;14;add_test;C:/Users/daris/Documents/Saclay/ReseauDeNeurones/nn/tests/CMakeLists.txt;0;")
else()
  add_test(test_network NOT_AVAILABLE)
endif()
